databases:
  - name: afex_app
    databaseName: afex_app
    user: afex_app

services:
  - type: web
    name: afex_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn afex_app.wsgi:application"
    envVars:
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: afex_app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
