# Generated by Django 4.0.6 on 2022-07-26 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(help_text='Friends of the user', to=settings.AUTH_USER_MODEL),
        ),
    ]
