# Generated by Django 4.0.6 on 2022-07-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed_at',
        ),
    ]
