# Generated by Django 4.0.6 on 2022-07-27 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='Chat messages', max_length=500, null=True)),
                ('location', models.URLField(help_text='A location url', null=True)),
                ('file', models.CharField(help_text='File to be shared', max_length=255, null=True)),
                ('receiver', models.ForeignKey(help_text='The receiver of this chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The initiator of this chat.', on_delete=django.db.models.deletion.CASCADE, related_name='chats_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
